### ISSUE TITLE
Not Available on Atlassian Marketplace

### ISSUE THREAD

**Issue by madkins1868** [microsoft/azure-pipelines-jira#44]
The link on the wiki no longer works and this doesn't appear to be available in the Atlassian marketplace anymore.   Is this a temporary problem or is this gone for good?

**Comment by chelseasaffold** [comment]
Same here

**Comment by vanmash** [comment]
@shashban Is it alive?

**Comment by tdkeepings** [comment]
Same here. I've had a scout around and can't find anything else that does similar so would be a shame if this project has died!

**Comment by patcor** [comment]
Microsoft support told me that they are working on an update/fix for the plugin, but it will take a couple of weeks before it will be available in the marketplace again.

**Comment by pmaronna** [comment]
Same problem here... is this project alive?

**Comment by StingyJack** [comment]
> Microsoft support told me that they are working on an update/fix for the plugin, but it will take a couple of weeks before it will be available in the marketplace again.

I was told this same thing in January.  If I knew what to do with the files in this repo I'd like to try and run with it but I dont even know what it is I am looking at other than a pile of XML files.

**Comment by ozbillwang** [comment]
have no chance to use it. 

anyone can confirm if this plug-in can manage Azure DevOps git repositoies as well or not?

I just need a plug-in to connect jira to Azure DevOps git repositories, that I can create branches from jira with azure repos directly

<img width="452" alt="image" src="https://user-images.githubusercontent.com/8954908/173721153-5fba9c41-0c44-4529-a9a0-cc6b576baf1b.png">

**Comment by IlyaSemenchenkoIfs** [comment]
We also need this plugin, any updates?

**Comment by mitchbArinco** [comment]
Also need this plugin

**Comment by tdkeepings** [comment]
@patcor have you heard any other updates from Microsoft about this?

**Comment by marncosta** [comment]
I found it on atlassian marketplace but it is not working anymore. It does not appear on Azure Devops service connection page. When I try to install manually, I got "Only service principal identity is allowed to perform this operation."

**Comment by jonayrb** [comment]
Have somebody any news about when the extension can be online again? . Thanks

**Comment by DarthSonic** [comment]
Here are two feedback links for Visual Studio about this topic here. Would appreciate if you will upvote them:

https://developercommunity.visualstudio.com/t/Deployments-are-not-reported-to-Jira-Aut/10083650
https://developercommunity.visualstudio.com/t/Azure-Pipelines-for-JIRA-Disappeared-Fro/10040745

**Comment by StingyJack** [comment]
> Would appreciate if you will upvote them:

Done. Hopefully my comment to the triage team that is delaying your issue helps them to understand the situation and the right way to handle a ticket

**Comment by jamesnwarner** [comment]
I just checked this morning and the application appears to be available in the Atlassian Marketplace again.

[https://marketplace.atlassian.com/apps/1220515/azure-pipelines-for-jira?hosting=cloud&tab=overview](https://marketplace.atlassian.com/apps/1220515/azure-pipelines-for-jira?hosting=cloud&tab=overview)

**Comment by DarthSonic** [comment]
> I just checked this morning and the application appears to be available in the Atlassian Marketplace again.
> 
> https://marketplace.atlassian.com/apps/1220515/azure-pipelines-for-jira?hosting=cloud&tab=overview

Yes. But unfortunately builds and deployments are still not reported to Jira. Maybe we need to set it up completely fresh.

**Comment by mhousaini-aware** [comment]
> > I just checked this morning and the application appears to be available in the Atlassian Marketplace again.
> > https://marketplace.atlassian.com/apps/1220515/azure-pipelines-for-jira?hosting=cloud&tab=overview
> 
> Yes. But unfortunately builds and deployments are still not reported to Jira. Maybe we need to set it up completely fresh.

I'm considering uninstalling and re-installing it to see if it starts working again. Has anyone tried this?

**Comment by jamesnwarner** [comment]
I just installed fresh this morning for the first time on our Jira instance but can confirm I am experiencing what @DarthSonic said.

Our builds and deployments are not being reported to Jira, even though the setting is enabled in Azure DevOps.

**Comment by DarthSonic** [comment]
I tried to install fresh by removing the app from Jira and reinstalling. Unfortunately the organization is restored and I cannot remove it: 
![image](https://user-images.githubusercontent.com/3968605/184838595-29b19436-f0d0-48c9-8e9e-9fcd117236c5.png)

**Comment by tdkeepings** [comment]
Is it dead, Jim?
